server:
  port: 8080

spring:
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}
logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

aws:
  s3:

    endpoint: ${MINIO_ENDPOINT}

    access-key: ${AWS_S3_ACCESS_KEY}
    secret-key: ${AWS_S3_SECRET_KEY}

    bucket-name: study-media

    region: us-east-1

    path-style-access-enabled: true


cors:
  shell-app-local: http://localhost:4200
  mfe-study-local: http://localhost:4201
  prod: ${CORS_PROD}
