server:
  port: 8080

spring:
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}
logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

# src/main/resources/application.yml

# --- Configuração do MinIO (S3 Compatível) ---
aws:
  s3:

    endpoint: http://192.168.0.50:9000

    access-key: ${AWS_S3_ACCESS_KEY}
    secret-key: ${AWS_S3_ACCESS_KEY}

    bucket-name: study-media

    region: us-east-1

    path-style-access-enabled: true

