name: Build, Deploy and Restart Spring Boot App

on:
  push:
    branches:
      - main

jobs:
  deploy-to-server:
    runs-on: self-hosted

    environment: study-secrets

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        run: mvn -B package --file pom.xml -DskipTests

      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            echo "SPRING_DATA_MONGODB_URI=${{ secrets.MONGO_URI }}" > /home/${{ secrets.USERNAME }}/prod.env
            echo "AWS_S3_ACCESS_KEY=${{ secrets.MINIO_ACCESS_KEY }}" >> /home/${{ secrets.USERNAME }}/prod.env
            echo "AWS_S3_SECRET_KEY=${{ secrets.MINIO_SECRET_KEY }}" >> /home/${{ secrets.USERNAME }}/prod.env

            scp -o StrictHostKeyChecking=no target/*.jar ${{ secrets.USERNAME }}@${{ secrets.HOST }}:/home/${{ secrets.USERNAME }}/sua-app.jar

            ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.HOST }} "sudo systemctl restart spring-app.service"