name: Build, Deploy and Restart Spring Boot App

on:
  push:
    branches:
      - main

jobs:
  deploy-to-server:
    runs-on: self-hosted
    environment: study-secrets

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        run: mvn -B package --file pom.xml -DskipTests

      - name: Rename Artifact for Consistent Deployment
        run: mv target/*.jar target/app.jar
        shell: bash

      - name: Copy Artifact to Server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: "target/app.jar"
          target: "/home/${{ secrets.USERNAME }}/"
          overwrite: true

      - name: Deploy and Restart Application
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            APP_HOME="/home/${{ secrets.USERNAME }}"
            ENV_FILE_PATH="/etc/default/spring-app"

            echo "Garantindo a posse do artefato para o usuário deployer..."
            sudo chown ${{ secrets.USERNAME }}:${{ secrets.USERNAME }} $APP_HOME/app.jar

            echo "Criando/Atualizando o arquivo de ambiente em $ENV_FILE_PATH..."
            echo "SPRING_DATA_MONGODB_URI=${{ secrets.MONGO_URI }}" | sudo tee $ENV_FILE_PATH > /dev/null
            echo "AWS_S3_ACCESS_KEY=${{ secrets.AWS_S3_ACCESS_KEY }}" | sudo tee -a $ENV_FILE_PATH > /dev/null
            echo "AWS_S3_SECRET_KEY=${{ secrets.AWS_S3_SECRET_KEY }}" | sudo tee -a $ENV_FILE_PATH > /dev/null
            echo "MINIO_ENDPOINT=${{ secrets.MINIO_ENDPOINT }}" | sudo tee -a $ENV_FILE_PATH > /dev/null
            echo "CORS_PROD=${{ secrets.CORS_PROD }}" | sudo tee -a $ENV_FILE_PATH > /dev/null
            
            
            echo "Ajustando permissões do arquivo de ambiente..."
            sudo chmod 644 $ENV_FILE_PATH
            
           
            echo "Recarregando o daemon do systemd..."
            sudo systemctl daemon-reload


            echo "Reiniciando o serviço spring-app..."
            sudo systemctl restart spring-app.service

            sleep 5
            echo "Verificando o status do serviço..."
            sudo systemctl status spring-app.service --no-pager || echo "Falha ao verificar o status, mas o deploy continuou."

